---
- hosts: development
  become: yes
  gather_facts: no
  remote_user: {{ remote_user }}

  tasks:

  - name: install ssh key
    authorized_key: user = {{ user }}
                    key="{{ lookup('file', '/root/.ssh/id_rsa.pub') }}" 
                    state = present
